Server = true
Client = false
Addr = "9999"
Url = "https://github.com/rescuezilla/rescuezilla/releases/download/2.5.1/rescuezilla-2.5.1-64bit.noble.iso"
List = "192.168.0.100,192.168.0.99"
Clients = ["192.168.0.100", "192.168.0.99"]
CfgFile = "config.toml"
FileName = ""
OutputPath = "./temp"
