Server = true
Client = false
Addr = "9999"
Url = "https://go.p2hp.com/dl/go1.17.3.windows-amd64.msi"
List = "192.168.0.100,192.168.0.99"
Clients = ["192.168.0.100", "192.168.0.99"]
CfgFile = "config.toml"
FileName = ""
